# Generated by Django 4.2.5 on 2024-11-09 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100, unique=True)),
                ('correo', models.EmailField(max_length=100)),
                ('contrasena', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol', to='api_pago.rol')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenesPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_ingreso', models.DateField(auto_now_add=True)),
                ('acreedor', models.CharField(max_length=100)),
                ('factura', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(max_length=100)),
                ('documentacion_compensacion', models.CharField(max_length=100)),
                ('fecha_factura', models.DateField()),
                ('fecha_pago', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('urgente', models.CharField(max_length=100)),
                ('fecha_revisado', models.DateField()),
                ('id_analista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analista', to='api_pago.usuario')),
                ('id_coordinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinador', to='api_pago.usuario')),
                ('id_estado_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_pago', to='api_pago.estadopago')),
                ('id_tipo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_pago', to='api_pago.tipopago')),
            ],
        ),
        migrations.CreateModel(
            name='Devoluciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_devolucion', models.DateField(auto_now_add=True)),
                ('cedula_usuario_devolucion', models.IntegerField()),
                ('id_analista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analista_devolucion', to='api_pago.usuario')),
                ('id_orden_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orden_pago', to='api_pago.ordenespago')),
                ('id_tipo_devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_devolucion', to='api_pago.tipodevolucion')),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla', models.CharField(max_length=100)),
                ('columna', models.CharField(max_length=100)),
                ('valor_anterior', models.CharField(max_length=100)),
                ('valor_despues', models.CharField(max_length=100)),
                ('fecha_movimiento', models.DateField(auto_now_add=True)),
                ('transaccion', models.CharField(max_length=100)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='api_pago.usuario')),
            ],
        ),
    ]
