# Generated by Django 4.2.5 on 2024-11-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_pago', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.BigIntegerField(unique=True),
        ),
    ]
