# Generated by Django 4.2.5 on 2024-11-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_pago', '0004_alter_bitacora_columna_alter_bitacora_tabla_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devoluciones',
            name='cedula_usuario_devolucion',
            field=models.BigIntegerField(null=True),
        ),
    ]
