# Generated by Django 4.2.5 on 2024-12-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_pago', '0005_alter_devoluciones_cedula_usuario_devolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='nombre_rol',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
