# Generated by Django 4.2.5 on 2024-12-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_pago', '0006_alter_rol_nombre_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devoluciones',
            name='cedula_usuario_devolucion',
        ),
        migrations.AddField(
            model_name='devoluciones',
            name='Acreedor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
